[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = ["mkdir"]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = ["ls", "Select-Object"]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = ["Get-ChildItem", "Select-Object"]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = ["New-Item"]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = ["node"]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = ["Get-Content"]
